---
abstract: 'Apply source filter on external module'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: filtered
recommends:
  Filter::tee: 0
  PPI: 0
requires:
  perl: 5.006
version: v0.0.7
